version: '3.7'
services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - json-server
      - react-app
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 4000 -w data.json
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./usr/src:/app