version: '3.7'
services:
  react-nginx-app:
    restart: always
    container_name: react-nginx-app
    build:
      context: .
      dockerfile: DockerfileJenkins.prod
    ports:
      - "3000:80"



