version: '3.7'
services:
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 4000 -w data.json
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
    restart: always

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./usr/src:/app