version: '3.7'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3600:3000'
    volumes:
      - ./usr/src:/app/src:ro
    env_file:
      - ./.env.local