version: '3.7'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
        # npm run build시 환경 변수 참조가 안되어 args로 전달하고, Dockerfile에서 변수로 사용한다.
      #      ports:
      #        - "8080:80"
      # 80: HTTP Port for NGINX Web Server
  nginx:
    container_name: nginx
    image: "nginx:sua" # : 뒤는 tag
    ports:
      - "80:80"